markup=none

[update]
command=echo "   $(total=$(checkupdates | wc -l) && [ "$total" -gt 0 ] && echo "$total |")"
interval=3600
color=#FFFFFF

[date]
command=echo "   $(date '+%a %d %b')"
interval=60
color=#FFFFFF

[time]
command=echo "   $(date '+%H:%M')"
interval=60
color=#FFFFFF

[separator]
command=echo "|"
interval=once
color=#FFFFFF

[volume]
command=echo "   $(pactl get-sink-volume @DEFAULT_SINK@ | awk -v RS='\r\n' -F'/' '{print $2}'  )"
interval=1
color=#FFFFFF

[memory]
command=echo "    $(free -h | awk '/^Mem:/ {printf "%.1f/%.1f GiB\n", $3, $2}')"
interval=1
color=#FFFFFF
